# ==============================================================================
# 📱 termux.properties - Configurações Avançadas e Teclas Virtuais do Termux
# ==============================================================================

# Barra de Teclas Extras Estendidas (Linha dupla com atalhos de programação e navegação)
extra-keys = [ \
  ['ESC', 'TAB', 'CTRL', 'ALT', {key: '-', popup: '_'}, {key: '/', popup: '\\'}, 'HOME', 'UP', 'END'], \
  ['QUOTE', 'APOSTROPHE', 'TILDE', 'PIPE', {key: '(', popup: ')'}, {key: '[', popup: ']'}, 'LEFT', 'DOWN', 'RIGHT'] \
]

# Comportamento do teclado e da interface
bell-character = ignore
fullscreen = false
use-black-ui = true
